kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-read-clusterrole-users
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
For each group that needs access:
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-read-clusterrolebinding-users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-read-clusterrole-users
subjects:

- kind: Group
  name: "dbf77f23-589c-40a5-5g6d-2aeec50f021e" #Group ID of users